"""add canonical job and job intelligence fields

Revision ID: 20614a934141
Revises: 9f216d211dac
Create Date: 2026-08-12 12:47:32.631653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '20614a934141'
down_revision: Union[str, None] = '9f216d211dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('hybrid', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('role_category', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('best_application_url', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_jobs_company_name'), 'canonical_jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_canonical_jobs_id'), 'canonical_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_jobs_title'), 'canonical_jobs', ['title'], unique=False)
    op.add_column('jobs', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('company_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('seniority', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('role_category', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('experience_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('application_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('canonical_job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'canonical_jobs', ['canonical_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'canonical_job_id')
    op.drop_column('jobs', 'application_url')
    op.drop_column('jobs', 'experience_max')
    op.drop_column('jobs', 'experience_min')
    op.drop_column('jobs', 'skills')
    op.drop_column('jobs', 'role_category')
    op.drop_column('jobs', 'seniority')
    op.drop_column('jobs', 'company_url')
    op.drop_column('jobs', 'company_name')
    op.drop_index(op.f('ix_canonical_jobs_title'), table_name='canonical_jobs')
    op.drop_index(op.f('ix_canonical_jobs_id'), table_name='canonical_jobs')
    op.drop_index(op.f('ix_canonical_jobs_company_name'), table_name='canonical_jobs')
    op.drop_table('canonical_jobs')
    # ### end Alembic commands ###
