"""Add JobSource and update Profile

Revision ID: 28ea02d7bb31
Revises: 336538b85113
Create Date: 2026-08-08 13:10:41.138906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ea02d7bb31'
down_revision: Union[str, None] = '336538b85113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_name'), 'job_sources', ['name'], unique=False)
    op.add_column('profiles', sa.Column('college', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('school', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('projects', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'projects')
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'school')
    op.drop_column('profiles', 'college')
    op.drop_index(op.f('ix_job_sources_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
