"""add user profile and job match tables

Revision ID: 294d83fa508a
Revises: 20614a934141
Create Date: 2026-08-12 12:51:02.595176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '294d83fa508a'
down_revision: Union[str, None] = '20614a934141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canonical_job_id', sa.Integer(), nullable=False),
    sa.Column('skill_match', sa.Float(), nullable=True),
    sa.Column('role_match', sa.Float(), nullable=True),
    sa.Column('experience_match', sa.Float(), nullable=True),
    sa.Column('location_match', sa.Float(), nullable=True),
    sa.Column('salary_match', sa.Float(), nullable=True),
    sa.Column('education_match', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['canonical_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_canonical_job_id'), 'job_matches', ['canonical_job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_job_matches_match_score'), 'job_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('preferred_roles', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('salary_preferences', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.Boolean(), nullable=True),
    sa.Column('profile_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_match_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_canonical_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
