"""add ingestion tracking fields

Revision ID: 9f216d211dac
Revises: ab2b5ceb251f
Create Date: 2026-08-12 12:19:38.409987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f216d211dac'
down_revision: Union[str, None] = 'ab2b5ceb251f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_period', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('city', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('state', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('country', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('hybrid', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('validation_status', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('extraction_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'extraction_method')
    op.drop_column('jobs', 'validation_status')
    op.drop_column('jobs', 'extraction_confidence')
    op.drop_column('jobs', 'hybrid')
    op.drop_column('jobs', 'country')
    op.drop_column('jobs', 'state')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'salary_period')
    # ### end Alembic commands ###
