"""Refactor job source and job models for ingestion

Revision ID: ab2b5ceb251f
Revises: 4f7a9c635463
Create Date: 2026-08-11 23:57:41.848717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2b5ceb251f'
down_revision: Union[str, None] = '4f7a9c635463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_sources', sa.Column('crawl_frequency', sa.Integer(), nullable=True))
    op.add_column('job_sources', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('job_sources', sa.Column('last_success_at', sa.DateTime(), nullable=True))
    op.add_column('job_sources', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('job_sources', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('job_sources', sa.Column('last_modified', sa.String(), nullable=True))
    op.add_column('job_sources', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('job_sources', sa.Column('configuration', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('remote', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('first_seen_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('last_changed_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'content_hash')
    op.drop_column('jobs', 'last_changed_at')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'first_seen_at')
    op.drop_column('jobs', 'raw_data')
    op.drop_column('jobs', 'source_name')
    op.drop_column('jobs', 'source_type')
    op.drop_column('jobs', 'source_url')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'posted_at')
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'remote')
    op.drop_column('jobs', 'external_id')
    op.drop_column('job_sources', 'configuration')
    op.drop_column('job_sources', 'content_hash')
    op.drop_column('job_sources', 'last_modified')
    op.drop_column('job_sources', 'etag')
    op.drop_column('job_sources', 'last_error')
    op.drop_column('job_sources', 'last_success_at')
    op.drop_column('job_sources', 'last_checked_at')
    op.drop_column('job_sources', 'crawl_frequency')
    # ### end Alembic commands ###
