"""add_scraper_rules_table

Revision ID: d18ecd7d40fa
Revises: 294d83fa508a
Create Date: 2026-08-23 00:11:46.099112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18ecd7d40fa'
down_revision: Union[str, None] = '294d83fa508a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('healing_attempt_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version', name='uix_source_id_version')
    )
    op.create_index(op.f('ix_scraper_rules_domain'), 'scraper_rules', ['domain'], unique=False)
    op.create_index(op.f('ix_scraper_rules_id'), 'scraper_rules', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_rules_source_id'), 'scraper_rules', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_rules_source_id'), table_name='scraper_rules')
    op.drop_index(op.f('ix_scraper_rules_id'), table_name='scraper_rules')
    op.drop_index(op.f('ix_scraper_rules_domain'), table_name='scraper_rules')
    op.drop_table('scraper_rules')
    # ### end Alembic commands ###
