from sqlalchemy import Column, Integer, Float, ForeignKey, Boolean, JSON
from sqlalchemy.orm import relationship
from db.base_class import Base

class JobMatch(Base):
    __tablename__ = "job_matches"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    canonical_job_id = Column(Integer, ForeignKey("canonical_jobs.id"), nullable=False, index=True)
    
    # Sub-scores (0.0 to 1.0)
    skill_match = Column(Float, default=0.0)
    role_match = Column(Float, default=0.0)
    experience_match = Column(Float, default=0.0)
    location_match = Column(Float, default=0.0)
    salary_match = Column(Float, default=0.0)
    education_match = Column(Float, default=0.0)
    
    # Overall Score (0 to 100)
    match_score = Column(Float, default=0.0, index=True)
    
    # Ranking
    rank = Column(Integer, nullable=True)
    
    # Explanations generated by LLM
    match_reasons = Column(JSON, nullable=True)
    
    is_saved = Column(Boolean, default=False)
    
    user = relationship("User", backref="job_matches")
    canonical_job = relationship("CanonicalJob", backref="matches")
